--Verify all objects owned by user ESILVAS does exist in the database
SELECT * FROM ALL_OBJECTS
WHERE OWNER = 'IATA_OLAP';

SELECT * FROM ALL_TABLES
WHERE OWNER = 'IATA_OLAP';



SELECT * FROM ALL_TABLES;

SELECT * FROM IATA.AVIONES;

DROP TABLE DIM_AEROLINEA CASCADE CONSTRAINTS;
DROP TABLE DIM_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DIM_MODELO CASCADE CONSTRAINTS;
DROP TABLE DIM_RUTA CASCADE CONSTRAINTS;
DROP TABLE DIM_TIEMPO CASCADE CONSTRAINTS;
DROP TABLE FACT_VENTAS_VUELOS CASCADE CONSTRAINTS;

DROP SEQUENCE ISEQ$$_88190;
DROP SEQUENCE ISEQ$$_88190;

SELECT * FROM IATA.vuelos order by 1;



SELECT 
    u.NOMBRE || ' ' || u.APELLIDO AS PASAJERO,
    COUNT(*) AS TOTAL_VUELOS
FROM IATA.VUELOS v
JOIN IATA.USUARIOS u ON v.ID_USUARIO = u.CEDULA
GROUP BY u.NOMBRE, u.APELLIDO
ORDER BY TOTAL_VUELOS DESC;

-- Esto eliminará automáticamente la secuencia asociada
DROP TABLE FACT_VENTAS_VUELOS CASCADE CONSTRAINTS;



